# Wed, 27 Sep 2017 15:33:18 +0300
timestamp = 1506515598

[netvars]
m_ArmorValue = 45608
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14480
m_bHasDefuser = 45624
m_bHasHelmet = 45596
m_bInReload = 12869
m_bIsDefusing = 14468
m_bIsScoped = 14460
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12976
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41704
m_flFlashMaxAlpha = 41700
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13152
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 45716
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41728
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iObserverMode = 13132
m_iShotsFired = 41632
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13316
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13704
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304
m_zoomLevel = 13120

[signatures]
dwClientState_GetLocalPlayer = 384
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 784
dwClientState_PlayerInfo = 21056
dwClientState_State = 264
dwClientState_ViewAngles = 19728
dwEntityList = 78168108
dwForceAttack = 49079296
dwForceAttack2 = 49079308
dwForceBackward = 49079272
dwForceForward = 49079260
dwForceJump = 82980544
dwForceLeft = 49079236
dwForceRight = 49079248
dwGameDir = 6564816
dwGameRulesProxy = 83415564
dwGetAllClasses = 83415776
dwGlobalVars = 5914696
dwInput = 82668528
dwInterfaceLinkList = 7254916
dwLocalPlayer = 11201596
dwMouseEnable = 11224224
dwMouseEnablePtr = 11224176
dwPlayerResource = 49071932
dwRadarBase = 82578724
dwSetClanTag = 542960
dwViewMatrix = 78109298
dwZoomSensitivityRatioPtr = 11243880
dwbSendPackets = 830346
dwppDirect3DDevice9 = 663360
m_pStudioHdr = 10556
